JWT_SECRET_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3IiOiJncmFtb3MiLCJyb2wiOjEsImV4cCI6MTYzMjgyNDA3MX0.N1O2M5Z6YUwzux9SolM5HtAJC8SHimsbSqaw5KtGAAc"
JWT_ALGORITHM = "HS256"
JWT_EXPIRATION_TIME_MINUTES = 300  # incrementar al número de minutos que considere
JWT_VALID_ROLES = [1, 2]
